site_name: La pelle de Cthulhu, les masques de Nyarlathotep du vendredi
site_url: https://avados.github.io/CoC_Masques_de_Nyarlatothep/
repo_url: https://github.com/avados/CoC_Masques_de_Nyarlatothep

theme:
  name: material
  custom_dir: overrides
  features:
    - tabs
    - navigation.footer
    - navigation.tracking
    - navigation.top
    - search.highlight


nav:
    - Bienvenue: index.md
    - TODO: TODO.md
    - DONE: DONE.md
    - USA:
       - 7 octobre 2022: 7 octobre 2022.md
       - 21 octobre 2022: 21 octobre 2022.md
       - 4 novembre 2022: 4 novembre 2022.md
       - 18 novembre 2022: 18 novembre 2022.md
       - 2 décembre 2022: 2 decembre 2022.md
    - Angleterre:
      - 13 janvier 2022: 13 janvier 2022.md
      - 27 janvier 2023: 27 janvier 2023.md
      - 10 février 2023: 10 fevrier 2023.md
      - 24 février 2023: 24 fevrier 2023.md
    - Égypte:
        - 10 mars 2023: 10 mars 2023.md
        - 24 mars 2023: 24 mars 2023.md
        - 7 avril 2023: 7 avril 2023.md
        - 21 avril 2023: 21 avril 2023.md
    - Kenya: Kenya.md
    - Shangai: Shangai.md 
    - Personnalités:
        - Omar Shakti: Omar Shakti.md
        - Ali kafour: Ali kafour.md
        - Anthony Cowles: Anthony Cowles.md
        - Arthur Emerson: Arthur Emerson.md
        - Aubrey Penhew: Aubrey Penhew.md
        - Auguste Loret: Auguste Loret.md
        - Ayers rock: Ayers rock.md
        - Bastet: Bastet.md
        - Carlyle: Carlyle.md
        - Chauve souris des sables: Chauve souris des sables.md
        - Clyve: Clyve.md
        - Edward Gavigan: Edward Gavigan.md
        - Emerson import: Emerson import.md
        - Erica Carlyle: Erica Carlyle.md
        - Faraz nagir: Faraz nagir.md
        - George Osgood: George Osgood.md
        - Hakim: Hakim.md
        - Hirem: Hirem.md
        - Jackson Elias: Jackson Elias.md
        - James Barrington: James Barrington.md
        - Jonas Kensington: Jonas Kensington.md
        - Jujkui: Jujkui.md
        - Kikuyu: Kikuyu.md
        - M'weru: M'weru.md
        - Martin Poole: Martin Poole.md
        - Miriam Atwright: Miriam Atwright.md
        - Niktoris: Niktoris.md
        - Nyiti d'el Wasta: Nyiti d'el Wasta.md
        - Peuple Monolithe: Peuple Monolithe.md
        - Robert Huston: Robert Huston.md
        - Roger Carlyle: Roger Carlyle.md
        - Royston whittingdon: Royston whittingdon.md
        - San Mariga: San Mariga.md
        - Silas N'KwaneSi: Silas N'KwaneSi.md
        - Tewfik Al Sayed: Tewfik Al Sayed.md
        - Victoria Post: Victoria Post.md
        - anastasia: anastasia.md
        - chakota: chakota.md
        - culte de la langue sanglante: culte de la langue sanglante.md
        - dieu du vent noir: dieu du vent noir.md
        - jack Brady: jack Brady.md
        - johnstone kenyatta: johnstone kenyatta.md
        - lars torvak: lars torvak.md
        - lieutenant Mark Selkirk: lieutenant Mark Selkirk.md
        - mickey mahonay: mickey mahonay.md
        - moi: moi.md
        - nelson: nelson.md
        - Nyarlathotep: nyarlatotep.md
        - sebekh: sebekh.md
        
        
    - lieux:
        - stumbling tiger bar: stumbling tiger bar.md
        - victoria bar: victoria bar.md
        - shefford: shefford.md
        - shepheard: shepheard.md
        - prospero press: prospero press.md
        - repaire: repaire.md
        - musée du caire: musée du caire.md
        - mykelinos: mykelinos.md
        - nairobi: nairobi.md
        - juju: juju.md
        - la pyramide bleue: la pyramide bleue.md
        - Queens: Queens.md
        - empire spices: empire spices.md
        - fondation penhew: fondation penhew.md
        - fraternité du pharaon noir: fraternité du pharaon noir.md
        - Ho Fong Imports: Ho Fong Imports.md
        - Ibn Tulun: Ibn Tulun.md
        - Mombasa: mombasa.md

    - Objets:
        - lance de Neth: lance de Neth.md
        - Vie d'un dieu: Vie d'un dieu.md
        - Pnakotiques: Pnakotiques.md

plugins:
  - search
  - roamlinks
  - mkdocs-backlinks
  - glightbox
